In [26]:
# data parsed from coinmarketcap.com
import pandas as pd
example_df = pd.read_html('https://coinmarketcap.com/currencies/dogecoin/historical-data/?start=20130428&end=20191117')

In [9]:
example_df

[Empty DataFrame
 Columns: [Date, Open*, High, Low, Close**, Volume, Market Cap]
 Index: [], Empty DataFrame
 Columns: [Date]
 Index: [],               Date     Open*      High       Low   Close**       Volume  \
 0     Nov 16, 2019  0.002657  0.002675  0.002636  0.002669   71531457.0
 1     Nov 15, 2019  0.002682  0.002689  0.002609  0.002657   78888251.0
 2     Nov 14, 2019  0.002694  0.002698  0.002642  0.002680   77359949.0
 3     Nov 13, 2019  0.002723  0.002725  0.002665  0.002698   80974477.0
 4     Nov 12, 2019  0.002714  0.002735  0.002679  0.002725   72506822.0
 5     Nov 11, 2019  0.002775  0.002780  0.002669  0.002715   84608148.0
 6     Nov 10, 2019  0.002712  0.002785  0.002687  0.002775   96734959.0
 7     Nov 09, 2019  0.002654  0.002742  0.002650  0.002713   93120071.0
 8     Nov 08, 2019  0.002723  0.002731  0.002603  0.002653   88039087.0
 9     Nov 07, 2019  0.002628  0.002734  0.002608  0.002725   97141368.0
 10    Nov 06, 2019  0.002623  0.002650  0.002615  0.002628   88212203.0
 11    Nov 05, 2019  0.002613  0.002651  0.002575  0.002624   78458702.0
 12    Nov 04, 2019  0.002635  0.002645  0.002590  0.002614   64040500.0
 13    Nov 03, 2019  0.002627  0.002674  0.002622  0.002637   57894711.0
 14    Nov 02, 2019  0.002631  0.002651  0.002597  0.002627   63232423.0
 15    Nov 01, 2019  0.002617  0.002639  0.002591  0.002630   78282711.0
 16    Oct 31, 2019  0.002618  0.002675  0.002586  0.002615   72101942.0
 17    Oct 30, 2019  0.002656  0.002682  0.002597  0.002616   88132224.0
 18    Oct 29, 2019  0.002647  0.002728  0.002644  0.002655   84394749.0
 19    Oct 28, 2019  0.002656  0.002722  0.002629  0.002646   92231650.0
 20    Oct 27, 2019  0.002621  0.002747  0.002595  0.002654   99551356.0
 21    Oct 26, 2019  0.002684  0.002858  0.002591  0.002622  118574429.0
 22    Oct 25, 2019  0.002539  0.002714  0.002502  0.002684   98533278.0
 23    Oct 24, 2019  0.002491  0.002553  0.002451  0.002538   81190106.0
 24    Oct 23, 2019  0.002564  0.002587  0.002389  0.002495   79141247.0
 25    Oct 22, 2019  0.002773  0.002776  0.002560  0.002565   75521553.0
 26    Oct 21, 2019  0.002732  0.002813  0.002618  0.002774   82888436.0
 27    Oct 20, 2019  0.002742  0.002775  0.002685  0.002730   73744712.0
 28    Oct 19, 2019  0.002704  0.002795  0.002668  0.002743   69804524.0
 29    Oct 18, 2019  0.002757  0.002863  0.002668  0.002706   60909633.0
 ...            ...       ...       ...       ...       ...          ...
 2133  Jan 13, 2014  0.000344  0.000344  0.000260  0.000278     391890.0
 2134  Jan 12, 2014  0.000359  0.000375  0.000323  0.000345     296158.0
 2135  Jan 11, 2014  0.000373  0.000509  0.000334  0.000356     986660.0
 2136  Jan 10, 2014  0.000246  0.000374  0.000241  0.000373     570553.0
 2137  Jan 09, 2014  0.000227  0.000269  0.000212  0.000246     314644.0
 2138  Jan 08, 2014  0.000223  0.000238  0.000203  0.000228     174256.0
 2139  Jan 07, 2014  0.000255  0.000284  0.000220  0.000225     212892.0
 2140  Jan 06, 2014  0.000271  0.000290  0.000226  0.000255     265529.0
 2141  Jan 05, 2014  0.000300  0.000312  0.000247  0.000271     245107.0
 2142  Jan 04, 2014  0.000305  0.000321  0.000256  0.000301     313907.0
 2143  Jan 03, 2014  0.000353  0.000376  0.000293  0.000303     303106.0
 2144  Jan 02, 2014  0.000449  0.000449  0.000331  0.000353     318037.0
 2145  Jan 01, 2014  0.000423  0.000451  0.000423  0.000440     307917.0
 2146  Dec 31, 2013  0.000418  0.000466  0.000408  0.000422     273400.0
 2147  Dec 30, 2013  0.000452  0.000459  0.000416  0.000416     276660.0
 2148  Dec 29, 2013  0.000459  0.000492  0.000399  0.000454     360974.0
 2149  Dec 28, 2013  0.000524  0.000540  0.000458  0.000459     341581.0
 2150  Dec 27, 2013  0.000603  0.000628  0.000497  0.000522     477422.0
 2151  Dec 26, 2013  0.000588  0.000706  0.000543  0.000602          0.0
 2152  Dec 25, 2013  0.000686  0.000694  0.000558  0.000587          0.0
 2153  Dec 24, 2013  0.000450  0.000913  0.000450  0.000686          0.0
 2154  Dec 23, 2013  0.000313  0.000460  0.000294  0.000451          0.0
 2155  Dec 22, 2013  0.000391  0.000498  0.000280  0.000315          0.0
 2156  Dec 21, 2013  0.000700  0.000700  0.000354  0.000394          0.0
 2157  Dec 20, 2013  0.001143  0.001143  0.000662  0.000704          0.0
 2158  Dec 19, 2013  0.000395  0.001520  0.000328  0.001162          0.0
 2159  Dec 18, 2013  0.000267  0.000362  0.000205  0.000362          0.0
 2160  Dec 17, 2013  0.000207  0.000289  0.000116  0.000269          0.0
 2161  Dec 16, 2013  0.000299  0.000866  0.000150  0.000205          0.0
 2162  Dec 15, 2013  0.000559  0.000904  0.000290  0.000298          0.0

       Market Cap
 0      325863006
 1      324279637
 2      327123523
 3      329198491
 4      332513142
 5      331233144
 6      338534498
 7      330918440
 8      323568240
 9      332378117
 10     320462936
 11     319899214
 12     318630213
 13     321384942
 14     320192885
 15     320557236
 16     318711696
 17     318792235
 18     323421852
 19     322352881
 20     323238308
 21     319273922
 22     326793804
 23     309068054
 24     303741402
 25     312300057
 26     337678500
 27     332308205
 28     333752702
 29     329253022
 ...          ...
 2133     7601922
 2134     9207368
 2135     9264269
 2136     9440391
 2137     6035300
 2138     5422855
 2139     5198193
 2140     5711172
 2141     5883644
 2142     6323972
 2143     6162990
 2144     6935467
 2145     8335005
 2146     7689659
 2147     7270542
 2148     7634717
 2149     7374149
 2150     8016604
 2151     8836621
 2152     8194483
 2153     9075938
 2154     5644793
 2155     3706592
 2156     4360316
 2157     7284337
 2158    11150339
 2159     3188943
 2160     2169688
 2161     1509085
 2162     1960300

 [2163 rows x 7 columns]]

In [29]:
example_df[2].head()

,Date,Open*,High,Low,Close**,Volume,Market Cap
0,"Nov 16, 2019",0.002657,0.002675,0.002636,0.002669,71531457.0,325863006
1,"Nov 15, 2019",0.002682,0.002689,0.002609,0.002657,78888251.0,324279637
2,"Nov 14, 2019",0.002694,0.002698,0.002642,0.002680,77359949.0,327123523
3,"Nov 13, 2019",0.002723,0.002725,0.002665,0.002698,80974477.0,329198491
4,"Nov 12, 2019",0.002714,0.002735,0.002679,0.002725,72506822.0,332513142

In [24]:
import os
cwd = os.getcwd()

In [25]:
example_df[2].to_csv(cwd+'/dogecoin_data_uptodate.csv')